import turtle
import random

turtle.pensize(5)
turtle.shape("turtle")

turtle.left(90)
turtle.color(random.choice(["red","yellow","blue","green","orange"]))
turtle.forward(100)
turtle.right(90)
turtle.penup()
turtle.color(random.choice(["red","yellow","blue","green","orange"]))
turtle.forward(50)
turtle.pendown()
turtle.color(random.choice(["red","yellow","blue","green","orange"]))
turtle.forward(75)
turtle.right(90)
turtle.color(random.choice(["red","yellow","blue","green","orange"]))
turtle.forward(50)
turtle.right(90)
turtle.color(random.choice(["red","yellow","blue","green","orange"]))
turtle.forward(75)
turtle.left(90)
turtle.color(random.choice(["red","yellow","blue","green","orange"]))
turtle.forward(50)
turtle.left(90)
turtle.color(random.choice(["red","yellow","blue","green","orange"]))
turtle.forward(75)
turtle.penup()
turtle.color(random.choice(["red","yellow","blue","green","orange"]))
turtle.forward(50)
turtle.pendown()
turtle.color(random.choice(["red","yellow","blue","green","orange"]))
turtle.forward(75)
turtle.left(90)
turtle.color(random.choice(["red","yellow","blue","green","orange"]))
turtle.forward(50)
turtle.left(90)
turtle.color(random.choice(["red","yellow","blue","green","orange"]))
turtle.forward(45)
turtle.left(180)
turtle.color(random.choice(["red","yellow","blue","green","orange"]))
turtle.forward(45)
turtle.left(90)
turtle.color(random.choice(["red","yellow","blue","green","orange"]))
turtle.forward(50)
turtle.left(90)
turtle.color(random.choice(["red","yellow","blue","green","orange"]))
turtle.forward(75)

turtle.exitonclick()
